accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include
from .views import CustomLoginView

app_name = "accounts"

urlpatterns = [
    path("home/", views.home, name="home"),
    # 以下はadminのログアウトになる
    # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # 現状このログアウトをしても、再度ログイン不要でhomeに入れてしまう
    # path(
    #     "",
    #     views.CustomLogoutView.as_view(template_name="accounts/login.html"),
    #     name="logout",
    # ),
    # path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("logout/", views.logout, name="logout"),
    # path("", views.CustomLoginView.as_view(), name="login"),
    path("", views.CustomLoginView.as_view(), name="login"),
    # path("", views.login, name="login"),
    # Minatotest
    path("navbase/", views.navbase, name="navbase"),
]

anoapp/urls.py
from django.urls import path
from . import views

from django.contrib import admin


urlpatterns = [
    # ◆Class BaseView
    # 0_admin用
    # path("admin/", admin.site.urls),
    # 1_anoappアプリのルートページ。(プロジェクトのurls.pyにて”anoapp”をアプリのルートページに設定している為!!)
    # （EX. http://127.0.0.1/anoapp/）
    path("", views.QuotationListlView.as_view(), name="list-page"),
    # 2_見積書新規作成画面（EX. http://127.0.0.1/anoapp/create/）
    path("create/", views.HeaderCreateView.as_view(), name="header_main_create"),
    # 3_見積書編集画面（EX. http://127.0.0.1/anoapp/update/1）
    path(
        "update/<int:pk>",
        views.HeaderUpdateView.as_view(),
        name="header_main_update",
    ),
    # 4_見積書削除画面（EX. http://127.0.0.1/anoapp/delete/1）
    path(
        "delete/<int:pk>", views.HeaderDeleteView.as_view(), name="header_main_delete"
    ),
    # ◆function BaseView
    #
    # 1_見積書検索結果画面
    path("quotation_list/", views.quotation_list, name="quotation_list"),
    # 2_見積書複製画面（EX. http://127.0.0.1/anoapp/duplicate/1）
    path("duplicate/<int:id>", views.duplicate_quotation, name="duplicate"),
    # path("duplicate/<int:pk>", views.duplicate_quotation, name="duplicate"),
    # 3_見積書PDFプレビュー画面
    path("pdf_preview/<int:pk>", views.pdf_preview_view, name="pdf_preview"),
]

book/urls.py
from django.urls import path
from .views import BookList,BookDetail
from .viewsDdt2 import FilterdBookList
from .viewsSd import BookListWithAjaxDT
from .viewsDt import DTBookList
from .viewsJson import book_json,jhome



#app_name = "Book"
urlpatterns = [
    #Bootstrap5 and CBV are used
    path('', BookList.as_view(), name='book-list'),
    
    #django-table2,django-filters packages are used
    path('ddt2/', FilterdBookList.as_view(), name='ddt2book-list'),
    
    #django-serverside-datatable is used
    #https://pypi.org/project/django-serverside-datatable/
    path('sd/', BookListWithAjaxDT.as_view(), name='sdbook-list'),
    
    #datatable is used
    path('dt/', DTBookList.as_view(), name='dtbook-list'),
    
    #JSON output for connection datatable with ajax  
    #JSON Response
    path('json/', jhome,name='jsbook-list'),
    #Json output
    path('json/source/', book_json, name='jsbook-source'),
    
    path('book/<int:pk>/', BookDetail.as_view(), name='book-detail'),
]

znwproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path("admin/", admin.site.urls),
    # HOME 暫定です
    # namespace="default" がないとURL namespaceがユニークではないと警告が出てしまう
    path("", include("accounts.urls", namespace="default")),
    # path("", include("anoapp.urls")),
    # wakamatsu test
    path("anoapp/", include("anoapp.urls")),  # その他製品見積システム
    # for testing joonhak
    path("sfa/", include("opportunity.urls")),  # 登録案件一覧
    path("contr/", include("neocontr.urls")),  # 契約一覧
    # Minato
    path("accounts/", include("accounts.urls")),
    # 管理画面_
    path("admin/", admin.site.urls),
]

anoapp/views.py
from django.shortcuts import render, redirect, reverse
from django.forms import formset_factory, inlineformset_factory
from django.db.models import Q
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import F
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required  # 追加


from django.http import HttpResponse
import json
import base64

# pdfプレビュー関連
from .estimatepdf_main import ExeMakeEstimatePdf
from django.http import HttpResponse

# add
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from .models import (
    AnotherQuotationHeader,
    AnotherQuotationMain,
    AnotherQuotationNotes,
    AnotherQuotationConfirm,
)

from .forms import (
    AnotherHeaderForm,
    AnotherMainForm,
    AnotherNotesForm,
    AnotherConfirmForm,
    AnotherMainFormSet,
    AnotherNotesFormSet,
    AnotherConfirmFormSet,
)

from django.urls import reverse_lazy

from django.forms import modelformset_factory, inlineformset_factory

from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _


####### クラスVIEW定義 ############################
#
#
# 01_その他プロダクト見積書_一覧画面
#
class QuotationListlView(LoginRequiredMixin, ListView):
    # 表示するtemplate名称
    template_name = "anoapp/quotation_list.html"
    # 利用モデル
    model = AnotherQuotationHeader

    # quotation_id列を降順に並べ替え
    header_list = model.objects.order_by(F("quotation_id").desc())

    # レコード情報をテンプレートに渡すオブジェクト(指定のモデルのオブジェクトを含むクエリセット)
    context_object_name = "header_list"

    # 1ページあたりの表示レコード件数
    paginate_by = 12

    # ページネーションを行う場合にqueryset属性
    queryset = AnotherQuotationHeader.objects.order_by(F("quotation_id").desc())


# 02_その他プロダクト見積書_新規作成画面
#
class HeaderCreateView(LoginRequiredMixin, CreateView):
    model = AnotherQuotationHeader
    form_class = AnotherHeaderForm
    template_name = "anoapp/quotation_create.html"

    def get_success_url(self):
        # 保存して戻るボタン
        if "save_and_back" in self.request.POST.values():
            return reverse_lazy("list-page")
        # 保存してするボタン
        else:
            return reverse_lazy("header_main_update", args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 新規作成画面は初期行を5行に設定
        AnotherMainFormSet = inlineformset_factory(
            AnotherQuotationHeader,
            AnotherQuotationMain,
            form=AnotherMainForm,
            extra=5,  # extraを設定
            can_delete=True,
        )
        AnotherNotesFormSet = inlineformset_factory(
            AnotherQuotationHeader,
            AnotherQuotationNotes,
            form=AnotherNotesForm,
            extra=2,  # extraを設定
        )
        AnotherConfirmFormSet = inlineformset_factory(
            AnotherQuotationHeader,
            AnotherQuotationConfirm,
            form=AnotherConfirmForm,
            extra=2,  # extraを設定
        )
        if self.request.POST:
            context["main_formset"] = AnotherMainFormSet(self.request.POST)
            context["notes_formset"] = AnotherNotesFormSet(self.request.POST)
            context["confirm_formset"] = AnotherConfirmFormSet(self.request.POST)
        else:
            context["main_formset"] = AnotherMainFormSet()
            context["notes_formset"] = AnotherNotesFormSet()
            context["confirm_formset"] = AnotherConfirmFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        main_formset = context["main_formset"]
        notes_formset = context["notes_formset"]
        confirm_formset = context["confirm_formset"]

        if (
            form.is_valid()
            and main_formset.is_valid()
            and notes_formset.is_valid()
            and confirm_formset.is_valid()
        ):
            self.object = form.save()
            main_formset.instance = self.object
            main_formset.save()
            notes_formset.instance = self.object
            notes_formset.save()
            confirm_formset.instance = self.object
            confirm_formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(
                form,
                main_formset=main_formset,
                notes_formset=notes_formset,
                confirm_formset=confirm_formset,
            )

    def form_invalid(
        self, form, main_formset=None, notes_formset=None, confirm_formset=None
    ):
        context = self.get_context_data(
            form=form,
            main_formset=main_formset,
            notes_formset=notes_formset,
            confirm_formset=confirm_formset,
        )
        return self.render_to_response(context)


# 03_その他プロダクト見積書_修正画面
#
class HeaderUpdateView(LoginRequiredMixin, UpdateView):
    model = AnotherQuotationHeader
    form_class = AnotherHeaderForm
    template_name = "anoapp/quotation_update.html"

    # 保存して戻る場合
    # success_url = reverse_lazy("list-page")

    # 保存して画面はそのままの場合
    # def get_success_url(self):
    #    return reverse_lazy("header_main_update", args=[self.object.pk])

    #
    def get_success_url(self):
        # 保存して戻るボタン
        if "save_and_back" in self.request.POST.values():
            return reverse_lazy("list-page")
        # 保存してするボタン
        else:
            return reverse_lazy("header_main_update", args=[self.object.pk])

    # GET、POSTリクエスト時。リクエストにより処理分岐
    def get_context_data(self, **kwargs):
        """
        テンプレートに渡すコンテキストデータを生成します。
        POSTリクエストの場合、POSTデータからフォームセットを生成します。
        GETリクエストの場合、空のフォームセットを生成します。
        """
        context = super().get_context_data(**kwargs)

        # 製品フォーム
        context["main_formset"] = AnotherMainFormSet(
            self.request.POST or None, instance=self.object
        )
        # 注釈フォーム
        context["notes_formset"] = AnotherNotesFormSet(
            self.request.POST or None, instance=self.object
        )
        # 社内確認欄フォーム
        context["confirm_formset"] = AnotherConfirmFormSet(
            self.request.POST or None, instance=self.object
        )
        return context

    # POSTリクエスト時
    # 各種フォームのバリデーションチェック
    def form_valid(self, form):
        # あなたが提供されたviewの定義
        context = self.get_context_data()
        main_formset = context["main_formset"]
        notes_formset = context["notes_formset"]
        confirm_formset = context["confirm_formset"]

        # 全てのフォームとフォームセットのバリデーションチェック
        if (
            form.is_valid()
            and main_formset.is_valid()
            and notes_formset.is_valid()
            and confirm_formset.is_valid()
        ):
            # 1_HeaderModelFormの保存
            #
            self.object = form.save()

            # 2_MainFormSetの保存
            #
            # MainFormSetの削除対象ModelFormを取得
            # メモ：inlines.jsのDELETEレコード。これがTRUEなら削除対象となる
            #       削除チェックボックスにチェックをしないと"DELETE"変数はcleaned_dateに現れないのでこのチェックをしてる
            deleted_main_forms = [
                f.instance for f in main_formset if f.cleaned_data.get("DELETE")
            ]

            # MainFormSetの保存
            main_formset.instance = self.object
            main_formset.save()

            # MainModelFormの保存
            for f in main_formset:
                f.save()

            # MainFormSetの削除対象ModelFormを削除
            for f in deleted_main_forms:
                f.delete()

            # 3_NotesFormSetの保存
            #
            # NotesFormSetの削除対象ModelFormを取得
            # メモ：inlines.jsのDELETEレコード。これがTRUEなら削除対象となる
            #       削除チェックボックスにチェックをしないと"DELETE"変数はcleaned_dateに現れないのでこのチェックをしてる
            deleted_notes_forms = [
                f.instance for f in notes_formset if f.cleaned_data.get("DELETE")
            ]

            # NotesFormSetの保存
            notes_formset.instance = self.object
            notes_formset.save()

            # NotesModelFormの保存
            for f in notes_formset:
                f.save()

            # NotesFormSetの削除対象ModelFormを削除
            for f in deleted_notes_forms:
                f.delete()

            # 4_ConfirmFormSetの保存
            #
            # ConfirmFormSetの削除対象ModelFormを取得
            # メモ：inlines.jsのDELETEレコード。これがTRUEなら削除対象となる
            #       削除チェックボックスにチェックをしないと"DELETE"変数はcleaned_dateに現れないのでこのチェックをしてる
            deleted_confirm_forms = [
                f.instance for f in confirm_formset if f.cleaned_data.get("DELETE")
            ]

            # ConfirmFormSetの保存
            confirm_formset.instance = self.object
            confirm_formset.save()

            # ConfirmModelFormの保存
            for f in confirm_formset:
                f.save()

            # ConfirmFormSetの削除対象ModelFormを削除
            for f in deleted_confirm_forms:
                f.delete()

            return super().form_valid(form)

        else:
            # バリデーションエラー時は全てのフォームを返す
            return self.render_to_response(
                self.get_context_data(
                    form=form,
                    main_formset=main_formset,
                    notes_formset=notes_formset,
                    confirm_formset=confirm_formset,
                )
            )

    # POSTリクエスト時
    # フォームの値検証がNGの場合
    def form_invalid(self, form, main_formset, notes_formset, confirm_formset):
        context = self.get_context_data(
            form=form,
            main_formset=main_formset,
            notes_formset=notes_formset,
            confirm_formset=confirm_formset,
        )
        return self.render_to_response(context)


# 04_その他プロダクト見積書_レコード削除画面
#
class HeaderDeleteView(LoginRequiredMixin, DeleteView):
    """
    見積書ヘッダの削除ビュー

    モデル: AnotherQuotationHeader
    テンプレート: "anoapp/quotation_delete.html"
    成功時のリダイレクト先: "list-page"
    """

    model = AnotherQuotationHeader
    template_name = "anoapp/quotation_delete.html"
    success_url = reverse_lazy("list-page")

anoapp/templates/base.html
<!--静的コンテンツ ロード-->
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<!--ヘッダー設定-->

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ZNW_その他製品見積書</title>

  <link rel="shortcut icon" href="{% static 'anoapp/img/favicon.png' %}" />


  <!--bootstrap関連-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

  <!--jquery関連 -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="{% static 'anoapp/js/inlines.js' %}"></script>
  <!--jquery関連
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  -->

  <!-- スタイルシート-->
  <link rel="stylesheet" type="text/css" href="{% static 'anoapp/css/another_app.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'common/Sandstone.css' %}" />

  <!--fontawesome-->
  <link href="https://use.fontawesome.com/releases/v6.4.2/css/all.css" rel="stylesheet">
</head>

<body>
  <!--ナビゲーションバーの設定-->
  <!-- Nav Bar -->
  <nav class="navbar navbar-expand-sm navbar-dark bg-info " style="--bs-bg-opacity:.5;">
    {% block navbar-content %}
    {% endblock navbar-content %}
    <div class="d-none d-md-block collapse navbar-collapse justify-content-end">

      <!--
      <div class="nav-item dropdown">
        <a class="btn btn-success me-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">その他製品見積</a>
                    <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="{% url 'list-page' %}">見積一覧</a></li>
          <li><a class="dropdown-item" href="{% url 'header_main_create' %}">新規作成</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="#">その他(工事中)</a></li>
          </ul>
      </div>
      -->

      {% if user.is_authenticated %}
      <a class="me-2 text-decoration-none" style="color:inherit"><b>@{{ user.get_username }}</b>でログイン中</a>
      {% endif %}

      <a class="btn btn-success me-2" role="button" href="{% url 'list-page' %}">見積一覧</a>
      <a class="btn btn-success me-2" role="button" href="{% url 'header_main_create' %}">新規作成</a>
      <a class="btn btn-warning me-2" role="button" href="{% url 'accounts:home' %}">HOME</a>
      <a class="btn btn-secondary me-2" role="button" href="{% url 'accounts:logout' %}">LOGOUT</a>

      <!--
      <a class="btn btn-primary me-2" role="button" href="{% url 'op-list' %}">登録案件一覧</a>
      <a class="btn btn-primary me-2" role="button" href="{% url 'ct-list' %}">契約一覧</a>
      -->


    </div>
  </nav>
  <!-- end Nav Bar-->

  <!--メイン部分-->
  {% comment %}
  <div class="container-fluid">{% block main %} {% endblock %}</div>
  {% endcomment %} {% block main %} {% endblock %}

  <!--スクリプト部分-->
  {% block scripts %}
  <!--Bootstrap用js-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  {% endblock %}
</body>

</html>

anoapp/templates/base_20231010.html
<!--静的コンテンツ ロード-->
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<!--ヘッダー設定-->

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ZNW_その他製品見積書</title>
  <link rel="shortcut icon" href="{% static 'anoapp/img/favicon.png' %}" />

  <!--bootstrap関連-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

  <!--jquery関連 -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="{% static 'anoapp/js/inlines.js' %}"></script>
  <!--jquery関連
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  -->

  <!-- スタイルシート-->
  <link rel="stylesheet" type="text/css" href="{% static 'anoapp/css/another_app.css' %}" />
</head>

<body>
  <!--ナビゲーションバーの設定-->
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
      <!--会社ロゴ-->
      <a class="navbar-brand" href="{% url 'list-page' %}">
        <img src="{% static 'anoapp/img/znwLogo.png' %}" alt="画像" />
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'list-page' %}">ホーム</a>
          </li>
          <!--ドロップダウンメニュー-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">システムメニュー
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item" href="{% url 'list-page' %}">見積書一覧</a>
              </li>
              <li>
                <a class="dropdown-item" href="/create/">新規作成</a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li><a class="dropdown-item" href="#">その他(工事中)</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">ヘルプ</a>
          </li>
        </ul>
        <!--
        <form class="d-flex">
          <input class="form-control me-2 h-25" type="search" placeholder="検索" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        -->
      </div>
    </div>
  </nav>

  <!--メイン部分-->
  {% comment %}
  <div class="container-fluid">{% block main %} {% endblock %}</div>
  {% endcomment %} {% block main %} {% endblock %}

  <!--スクリプト部分-->
  {% block scripts %}
  <!--Bootstrap用js-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  {% endblock %}
</body>

</html>

anoapp/templates/base_jqu追加前.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AnotherApp</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
</head>

<body>
  <!--ナビゲーションバー-->
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'list-page' %}">その他プロダクト見積りシステム</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'list-page' %}">Homeへ戻る</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">FAQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">ヘルプ</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!--メイン部分-->
  <div class="container-fluid">{% block main %} {% endblock %}</div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>

</html>

anoapp/templates/base_noInline.html
<!--静的コンテンツ ロード-->
{% load static %}

<!DOCTYPE html>
<html lang="ja">


<!--ヘッダー設定-->

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ZNW_その他製品見積書</title>
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

  <!--bootstrap関連-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

  <!--jquery関連 -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!--
  <script src="{% static 'js/inlines.js' %}"></script>
  -->

</head>

<body>

  <!--ナビゲーションバーの設定-->
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">

      <!--会社ロゴ-->
      <a class="navbar-brand" href="{% url 'list-page' %}">
        <img src="{% static 'img/znwLogo.png' %}" alt="画像">
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class=" nav-link active" aria-current="page" href="{% url 'list-page' %}">ホーム</a>
          </li>
          <!--ドロップダウンメニュー-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">システムメニュー
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'list-page' %}">見積書一覧</a></li>
              <li><a class="dropdown-item" href="/create/">新規見積書作成</a></li>
              <li><a class="dropdown-item" href="#">見積書修正</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">その他</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">ヘルプ</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2 h-25" type="search" placeholder="検索" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


  <!--メイン部分-->
  <div class="container-fluid">{% block main %} {% endblock %}</div>

  <!--スクリプト部分-->
  {% block scripts %}
  <!--Bootstrap用js-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  {% endblock %}


</body>

</html>